"""Add tenant session presence after the frozen workspace baseline."""

import sqlalchemy as sa
from alembic import op

revision = "20260927_presence"
down_revision = "20260927_workspace"
branch_labels = None
depends_on = None


def _create_table(name, *columns, **kwargs):
    inspector = sa.inspect(op.get_bind())
    if not inspector.has_table(name):
        op.create_table(name, *columns, **kwargs)
        return
    expected = {item.name for item in columns if isinstance(item, sa.Column)}
    actual = {item["name"] for item in inspector.get_columns(name)}
    if not expected <= actual:
        raise RuntimeError(
            f"Existing {name} has an unsupported schema; missing {expected - actual}"
        )


def _create_index(name, table, columns, unique=False, **kwargs):
    indexes = {item["name"]: item for item in sa.inspect(op.get_bind()).get_indexes(table)}
    if name in indexes:
        index = indexes[name]
        if index["column_names"] != columns or bool(index["unique"]) != unique:
            raise RuntimeError(f"Existing index {name} has an incompatible definition")
        return
    op.create_index(name, table, columns, unique=unique, **kwargs)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table(
        "workspace_session_presence",
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("since", sa.DateTime(), nullable=False),
        sa.Column("last_refresh", sa.DateTime(), nullable=False),
        sa.Column("task", sa.String(length=128), nullable=True),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "state IN ('idle','listening','thinking','working','draining','offline')",
            name="ck_presence_state",
        ),
        sa.CheckConstraint(
            "(user_id IS NOT NULL AND agent_id IS NULL) OR "
            "(user_id IS NULL AND agent_id IS NOT NULL)",
            name="ck_presence_identity",
        ),
        sa.CheckConstraint("tokens_in IS NULL OR tokens_in >= 0", name="ck_presence_tokens_in"),
        sa.CheckConstraint("tokens_out IS NULL OR tokens_out >= 0", name="ck_presence_tokens_out"),
        sa.ForeignKeyConstraint(
            ["org_id", "agent_id"],
            ["workspace_agents.org_id", "workspace_agents.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "channel_id"],
            ["workspace_rooms.org_id", "workspace_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "user_id"],
            ["workspace_members.org_id", "workspace_members.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("org_id", "session_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Presence downgrade would delete session data; restore a reviewed backup")
