"""Additive hosted workspace baseline; local data remains local.

Revision ID: 20260927_workspace
This revision also adopts pre-migration workspace previews after checking their
column layout. It never assigns legacy channels to a tenant or drops user data.
"""

import sqlalchemy as sa
from alembic import op

revision = "20260927_workspace"
down_revision = None
branch_labels = None
depends_on = None


def _create_table(name, *columns, **kwargs):
    inspector = sa.inspect(op.get_bind())
    if not inspector.has_table(name):
        op.create_table(name, *columns, **kwargs)
        return
    expected = {item.name for item in columns if isinstance(item, sa.Column)}
    actual = {item["name"] for item in inspector.get_columns(name)}
    if not expected <= actual:
        raise RuntimeError(
            f"Existing {name} has an unsupported schema; missing {expected - actual}"
        )


def _create_index(name, table, columns, unique=False, **kwargs):
    indexes = {item["name"]: item for item in sa.inspect(op.get_bind()).get_indexes(table)}
    if name in indexes:
        index = indexes[name]
        if index["column_names"] != columns or bool(index["unique"]) != unique:
            raise RuntimeError(f"Existing index {name} has an incompatible definition")
        return
    op.create_index(name, table, columns, unique=unique, **kwargs)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table(
        "workspace_users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    _create_table(
        "workspace_organizations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["workspace_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    _create_table(
        "workspace_agents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["workspace_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "id"),
    )
    _create_index(op.f("ix_workspace_agents_org_id"), "workspace_agents", ["org_id"], unique=False)
    _create_table(
        "workspace_audit",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["workspace_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    _create_index(op.f("ix_workspace_audit_org_id"), "workspace_audit", ["org_id"], unique=False)
    _create_table(
        "workspace_invitations",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["workspace_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["workspace_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("digest"),
    )
    _create_table(
        "workspace_members",
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["workspace_organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["workspace_users.id"],
        ),
        sa.PrimaryKeyConstraint("org_id", "user_id"),
    )
    _create_table(
        "workspace_rooms",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["workspace_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "id"),
        sa.UniqueConstraint("org_id", "name"),
    )
    _create_index(op.f("ix_workspace_rooms_org_id"), "workspace_rooms", ["org_id"], unique=False)
    _create_table(
        "workspace_credentials",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["workspace_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["workspace_users.id"],
        ),
        sa.PrimaryKeyConstraint("digest"),
    )
    _create_table(
        "workspace_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("room_id", sa.String(), nullable=False),
        sa.Column("sender_id", sa.String(), nullable=False),
        sa.Column("sender_name", sa.String(length=80), nullable=False),
        sa.Column("sender_kind", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "room_id"],
            ["workspace_rooms.org_id", "workspace_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["workspace_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "sender_id", "client_id"),
    )
    _create_index(
        op.f("ix_workspace_messages_org_id"), "workspace_messages", ["org_id"], unique=False
    )
    _create_index(
        op.f("ix_workspace_messages_room_id"), "workspace_messages", ["room_id"], unique=False
    )
    _create_index(
        "ux_workspace_message_tenant", "workspace_messages", ["org_id", "id"], unique=True
    )
    _create_table(
        "workspace_deliveries",
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.String(), nullable=False),
        sa.Column("recipient_name", sa.String(length=80), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id", "message_id"],
            ["workspace_messages.org_id", "workspace_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "recipient_id"],
            ["workspace_agents.org_id", "workspace_agents.id"],
        ),
        sa.PrimaryKeyConstraint("org_id", "message_id", "recipient_id"),
    )
    _create_index(
        "ix_workspace_pending",
        "workspace_deliveries",
        ["org_id", "recipient_id", "delivered_at", "message_id"],
        unique=False,
    )
    _create_table(
        "workspace_replies",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "message_id"],
            ["workspace_messages.org_id", "workspace_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "parent_id", "agent_id"],
            [
                "workspace_deliveries.org_id",
                "workspace_deliveries.message_id",
                "workspace_deliveries.recipient_id",
            ],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    _create_index(
        op.f("ix_workspace_replies_parent_id"), "workspace_replies", ["parent_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError(
        "Workspace downgrade would delete tenant data; restore a reviewed backup instead"
    )
